site_name: NEENO Docs
site_url: 'https://myneeno.com'
nav:
  - Home: index.md
  - Hardware: hardware.md
  - Software:
    - Overview: software.md
    - Intro: Software/introduction.md
  - About: about.md
theme:
  name: material
  locale: en
  logo: assets/Neeno-logo-light-gray.png
  favicon: assets/Neeno-logo-blue-50px.png
  font:
    text: Chivo light
  palette:
    primary: blue
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.sections
    - navigation.footer
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
extra_css:
  - extra.css
extra:
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/myneeno
    - icon: fontawesome/brands/github
      link: https://github.com/MyNeeno
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/company/neeno
    - icon: fontawesome/solid/envelope
      link: mailto:<contact@myneeno.com>
    - icon: fontawesome/solid/globe
      link: https://myneeno.com